name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    - name: configure
      run: qmake -config release
    - name: make
      run: make
    - name: Upload output file
      uses: actions/upload-artifact@v4
      with:
        name: output-compiled-file
        path: ReplacementWorkspace
